# Generated by Django 5.0.1 on 2024-01-07 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 1, 7, 19, 2, 11, 811296, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
